const paradas = [
    "Centro de Chapulhuacán",
    "Polvorin",
    "Puerto del caballo",
    "Plan de guadalupe",
    "Tamaulipas",
    "UTTT",
    "El barrio",
    "El entronque",
    "Puerto oscuro",
    "El amolar",
    "Santa maria",
    "Tejocote",
    "Santa ana",
    "Zacate grande",
    "La reforma",
    "El hualul",
    "El ocote",
    "Cantil del tambor",
    "Palomas",
    "El rayo"
];

const costos = {
    "Centro de Chapulhuacán": {
    "Polvorin": 11,
    "Puerto del caballo":11 ,
    "Plan de guadalupe": 11,
    "Tamaulipas": 14,
    "UTTT": 14,
    "El barrio": 14,
    "El entronque": 14 ,
    "Puerto oscuro":14 ,
    "El amolar":14,
    "Santa maria":14,
    "Tejocote": 14,
    "Santa ana":14 ,
    "Zacate grande":18 ,
    "La reforma":19,
    "El hualul": 19,
    "El ocote": 20,
    "Cantil del tambor": 24,
    "Palomas":25 ,
    "El rayo":35 ,
    },

"Polvorin": {
    "Centro de Chapulhuacán": 11,
    "Puerto del caballo": 11,
    "Plan de guadalupe": 11,
    "Tamaulipas": 14,
    "UTTT": 14,
    "El barrio": 14,
    "El entronque": 14,
    "Puerto oscuro": 14,
    "El amolar": 14,
    "Santa maria": 14,
    "Tejocote": 14,
    "Santa ana": 14,
    "Zacate grande": 18,
    "La reforma": 19,
    "El hualul": 19,
    "El ocote": 20,
    "Cantil del tambor": 24,
    "Palomas": 25,
    "El rayo": 35,
},
"Puerto del caballo": {
    "Centro de Chapulhuacán": 11,
    "Polvorin": 11,
    "Plan de guadalupe": 11,
    "Tamaulipas": 14,
    "UTTT": 14,
    "El barrio": 14,
    "El entronque": 14,
    "Puerto oscuro": 14,
    "El amolar": 14,
    "Santa maria": 14,
    "Tejocote": 14,
    "Santa ana": 14,
    "Zacate grande": 18,
    "La reforma": 19,
    "El hualul": 19,
    "El ocote": 20,
    "Cantil del tambor": 24,
    "Palomas": 25,
    "El rayo": 35,
},
"Plan de guadalupe": {
    "Centro de Chapulhuacán": 11,
    "Polvorin": 11,
    "Puerto del caballo": 11,
    "Tamaulipas":14,
    "UTTT":14,
    "El barrio":14,
    "El entronque":14,
    "Puerto oscuro":14,
    "El amolar": 14,
    "Santa maria": 14,
    "Tejocote": 14,
    "Santa ana": 14,
    "Zacate grande":17,
    "La reforma":18,
    "El hualul":20,
    "El ocote": 22,
    "Cantil del tambor": 22,
    "Palomas":24,
    "El rayo":34,
},
"Tamaulipas": {
    "Centro de Chapulhuacán":14,
    "Polvorin":14,
    "Puerto del caballo": 14,
    "Plan de guadalupe": 11,
    "UTTT":11,
    "El barrio":11,
    "El entronque":14,
    "Puerto oscuro":14,
    "El amolar": 14,
    "Santa maria": 14,
    "Tejocote": 14,
    "Santa ana": 14,
    "Zacate grande":17,
    "La reforma":18,
    "El hualul":18,
    "El ocote": 20,
    "Cantil del tambor": 20,
    "Palomas": 24,
    "El rayo": 33,
},
"UTTT": {
    "Centro de Chapulhuacán": 14,
    "Polvorin": 14,
    "Puerto del caballo": 14,
    "Plan de guadalupe": 11,
    "Tamaulipas":11,
    "El barrio":11,
    "El entronque":14,
    "Puerto oscuro":14,
    "El amolar": 14,
    "Santa maria": 14,
    "Tejocote": 14,
    "Santa ana": 14,
    "Zacate grande":17,
    "La reforma": 18,
    "El hualul": 18,
    "El ocote": 20,
    "Cantil del tambor": 22,
    "Palomas": 22,
    "El rayo": 25,
},
"El barrio": {
    "Centro de Chapulhuacán": 14,
    "Polvorin": 14,
    "Puerto del caballo": 14,
    "Plan de guadalupe": 11,
    "Tamaulipas":11,
    "UTTT":11,
    "El entronque":11,
    "Puerto oscuro":11,
    "El amolar": 11,
    "Santa maria": 11,
    "Tejocote": 11,
    "Santa ana": 11,
    "Zacate grande": 17,
    "La reforma": 17,
    "El hualul": 17,
    "El ocote": 17,
    "Cantil del tambor": 20,
    "Palomas": 20,
    "El rayo": 25,
},
"El entronque":{
    "Centro de Chapulhuacán": 14,
    "Polvorin": 14,
    "Puerto del caballo": 14,
    "Plan de guadalupe": 14,
    "Tamaulipas":11,
    "UTTT":11,
    "El barrio": 11,
    "Puerto oscuro": 11,
    "El amolar": 11,
    "Santa maria": 11,
    "Texocote": 11,
    "Santa ana": 11,
    "Zacate grande": 14,
    "La reforma": 14,
    "El hualul": 14,
    "El ocote": 16,
    "Cantil del tambor":16,
    "Palomas":18,
    "El rayo":25,
},
"Puerto oscuro": {
    "Centro de Chapulhuacán": 14,
    "Polvorin": 14,
    "Puerto del caballo": 14,
    "Plan de guadalupe": 14,
    "Tamaulipas":14,
    "UTTT":14,
    "El barrio":11,
    "El entronque":11,
    "El amolar":11,
    "Santa maria":11,
    "Tejocote":11,
    "Santa ana":11,
    "Zacate grande":14,
    "La reforma":14,
    "El hualul":14,
    "El ocote":16,
    "Cantil del tambor":16,
    "Palomas":18,
    "El rayo":25,
},
"El amolar":{
    "Centro de Chapulhuacán": 14,
    "Polvorin": 14,
    "Puerto del caballo": 14,
    "Plan de guadalupe": 14,
    "Tamaulipas":14,
    "UTTT":14,
    "El barrio": 14,
    "El entronque":11,
    "Puerto oscuro":11,
    "Santa maria":11,
    "Tejocote":11,
    "Santa ana":11,
    "Zacate grande":14,
    "La reforma":14,
    "El hualul":16,
    "El ocote":18,
    "Cantil del tambor":18,
    "Palomas":20,
    "El rayo":25,
},
"Santa maria":{
    "Centro de Chapulhuacán": 14,
    "Polvorin": 14,
    "Puerto del caballo": 14,
    "Plan de guadalupe": 14,
    "Tamaulipas":14,
    "UTTT":14,
    "El barrio": 14,
    "El entronque":11,
    "Puerto oscuro":11,
    "El amolar":11,
    "Tejocote":11,
    "Santa ana":11,
    "Zacate grande":14,
    "La reforma":14,
    "El hualul":15,
    "El ocote":16,
    "Cantil del tambor":16,
    "Palomas":20,
    "El rayo":25,
},
"Tejocote":{
    "Centro de Chapulhuacán": 14,
    "Polvorin": 14,
    "Puerto del caballo": 14,
    "Plan de guadalupe": 14,
    "Tamaulipas":14,
    "UTTT":14,
    "El barrio": 11,
    "El entronque":11,
    "Puerto oscuro":11,
    "El amolar":11,
    "Santa maria":11,
    "Santa ana":11,
    "Zacate grande":14,
    "La reforma":14,
    "El hualul":15,
    "El ocote":16,
    "Cantil del tambor":16,
    "Palomas":20,
    "El rayo":25,
},
"Santa ana":{
    "Centro de Chapulhuacán": 14,
    "Polvorin": 14,
    "Puerto del caballo": 14,
    "Plan de guadalupe": 14,
    "Tamaulipas":14,
    "UTTT":14,
    "El barrio": 11,
    "El entronque":11,
    "Puerto oscuro":11,
    "El amolar":11,
    "Santa maria":11,
    "Tejocote":11,
    "Zacate grande":14,
    "La reforma":14,
    "El hualul":15,
    "El ocote":16,
    "Cantil del tambor":16,
    "Palomas":20,
    "El rayo":25,
},
"Zacate grande":{
    "Centro de Chapulhuacán": 18,
    "Polvorin": 18,
    "Puerto del caballo": 18,
    "Plan de guadalupe": 17,
    "Tamaulipas":17,
    "UTTT":17,
    "El barrio":17,
    "El entronque":14,
    "Puerto oscuro":14,
    "El amolar":14,
    "Santa maria":14,
    "Tejocote":14,
    "Santa ana":14 ,
    "La reforma":11 ,
    "El hualul": 11,
    "El ocote": 11,
    "Cantil del tambor": 12,
    "Palomas":15 ,
    "El rayo":17 ,
},
"La reforma":{
    "Centro de Chapulhuacán": 19,
    "Polvorin": 19,
    "Puerto del caballo": 19,
    "Plan de guadalupe": 18,
    "Tamaulipas":18,
    "UTTT":18,
    "El barrio": 17,
    "El entronque":14,
    "Puerto oscuro":14,
    "El amolar":14,
    "Santa maria":14,
    "Tejocote":14,
    "Santa ana":11 ,
    "Zacate":11,
    "El hualul": 11,
    "El ocote": 11,
    "Cantil del tambor": 11,
    "Palomas":14 ,
    "El rayo":17 ,
},
"El hualul":{
    "Centro de Chapulhuacán": 19,
    "Polvorin": 19,
    "Puerto del caballo": 19,
    "Plan de guadalupe": 18,
    "Tamaulipas":18,
    "UTTT":18,
    "El barrio": 17,
    "El entronque":14,
    "Puerto oscuro":14,
    "El amolar":14,
    "Santa maria":14,
    "Tejocote":14,
    "Santa ana":11 ,
    "Zacate":11,
    "La reforma":11,
    "El ocote": 11,
    "Cantil del tambor": 11,
    "Palomas":14 ,
    "El rayo":17 ,
},
"El ocote":{
    "Centro de Chapulhuacán": 20,
    "Polvorin": 20,
    "Puerto del caballo": 20,
    "Plan de guadalupe": 17,
    "Tamaulipas":18,
    "UTTT":18,
    "El barrio": 18,
    "El entronque":17,
    "Puerto oscuro":16,
    "El amolar":15,
    "Santa maria":15,
    "Tejocote":15,
    "Santa ana":14 ,
    "Zacate":14,
    "La reforma":14,
    "El hualul":14,
    "Cantil del tambor": 14,
    "Palomas":14,
    "El rayo":15,
},
"Cantil del tambor":{
        "Centro de Chapulhuacán": 24,
        "Polvorin": 24,
        "Puerto del caballo": 24,
        "Plan de guadalupe": 20,
        "Tamaulipas":20,
        "UTTT":20,
        "El barrio": 18,
        "El entronque":16,
        "Puerto oscuro":16,
        "El amolar":16,
        "Santa maria":16,
        "Tejocote":16,
        "Santa ana":16,
        "Zacate":11,
        "La reforma":11,
        "El hualul":11,
        "El ocote":11,
        "Palomas":12 ,
        "El rayo":14 ,
},
"Palomas":{
        "Palomas": {
        "Centro de Chapulhuacán": 25,
        "Polvorin": 25,
        "Puerto del caballo": 25,
        "Plan de guadalupe": 24,
        "Tamaulipas": 24,
        "UTTT": 22,
        "Barrio": 20,
        "El entronque": 20,
        "Puerto oscuro": 20,
        "El amolar": 20,
        "Santa maria": 20,
        "Texocote": 20,
        "Santa ana": 20,
        "Zacate grande": 17,
        "La reforma": 17,
        "El hualul": 15,
        "El ocote": 15,
        "Cantil del tambor": 15,
        "El rayo": 14,
    },
},
"El rayo":{
    "Centro de Chapulhuacán": 35,
        "Polvorin": 35,
        "Puerto del caballo": 35,
        "Plan de guadalupe": 34,
        "Tamaulipas": 33,
        "UTTT": 33,
        "Barrio": 33,
        "El entronque": 28,
        "Puerto oscuro": 28,
        "El amolar": 26,
        "Santa maria": 25,
        "Texocote": 25,
        "Santa ana": 25,
        "Zacate grande": 17,
        "La reforma": 17,
        "El hualul": 17,
        "El ocote": 14,
        "Cantil del tambor": 14,
        "Palomas":11,
},
}

const origenSelect = document.getElementById("origen");
const destinoSelect = document.getElementById("destino");
const resultadoInput = document.getElementById("resultado");


paradas.forEach(parada => {
    const optionOrigen = document.createElement("option");
    optionOrigen.value = parada;
    optionOrigen.text = parada;
    origenSelect.appendChild(optionOrigen);

    const optionDestino = document.createElement("option");
    optionDestino.value = parada;
    optionDestino.text = parada;
    destinoSelect.appendChild(optionDestino);
});

// cambio de origen y destino
origenSelect.addEventListener("change", calcularCosto);
destinoSelect.addEventListener("change", calcularCosto);

function calcularCosto() {
    const origen = origenSelect.value;
    const destino = destinoSelect.value;

    if (origen === destino) {
        resultadoInput.value = "Origen y destino deben ser diferentes.";
        return;
    }

    if (costos[origen] && costos[origen][destino]) {
        resultadoInput.value = `$${costos[origen][destino]}`;
    } else if (costos[destino] && costos[destino][origen]) {
        resultadoInput.value = `$${costos[destino][origen]}`;
    } else {
        resultadoInput.value = "Costo no disponible.";
    }
}


